{% set name = "jobs_done10" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ESSS/jobs_done10/archive/{{ version }}.tar.gz
  sha256: a9e5c661dc668d7d2ec3befe3c1391ba4b60228c89de6a4245558a11ef79b5b9

build:
  noarch: python
  number: 0
  entry_points:
    - jobs_done=jobs_done10.cli:jobs_done
  script:
    - 'export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}'
    - '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - click
    - flask
    - mailer
    - pygments
    - python >=3.6
    - python-dotenv
    - python-jenkins
    - pyyaml

test:
  requires:
    - git
    - pytest
    - pytest-mock
    - requests-mock
  imports:
    - jobs_done10
    - jobs_done10._tests
    - jobs_done10.generators
    - jobs_done10.generators._tests
    - jobs_done10.xml_factory
    - jobs_done10.xml_factory._tests
  commands:
    - jobs_done --help
    - pytest --pyargs jobs_done10

about:
  home: https://github.com/ESSS/jobs_done10
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Job's Done uses a .jobs_done.yaml file in your repository to create Continuous Integration jobs on Jenkins.

extra:
  recipe-maintainers:
    - igortg
    - nicoddemus
    - tadeu
    - tarcisioe
