{% set python_min = '3.10' %}
{% set name = "jobs_done10" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ESSS/jobs_done10/archive/{{ version }}.tar.gz
  sha256: 292a2a2bb6fe2efa2a99944d72bb9e91018c365531af2ec7ec25df04a59c4f0f

build:
  noarch: python
  number: 1
  entry_points:
    - jobs_done=jobs_done10.cli:jobs_done
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - click
    - flask
    - gunicorn
    - pygments
    - python >={{ python_min }}
    - python-dotenv
    - python-jenkins
    - pyyaml

test:
  requires:
    - git
    - pytest-mock
    - pytest-regressions
    - requests-mock
    - python {{ python_min }}
  imports:
    - jobs_done10
  commands:
    - jobs_done --help

about:
  home: https://github.com/ESSS/jobs_done10
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Job's Done uses a .jobs_done.yaml file in your repository to create Continuous Integration jobs on Jenkins.

extra:
  recipe-maintainers:
    - igortg
    - nicoddemus
    - tadeu
    - tarcisioe
