travis:
  secure:
    BINSTAR_TOKEN: SOxjVyhUi38wb1kRUMqaBRH8qQORgkJ5QCOM79kiIxE91eQMMik6gaD5KFxjzsroiw+cy9wvLP5yLm7VIQYYM1KOQ0vJXpzaZaTK1ubg2gRBsv8xWvHsrTQBxYB/Cg1TviJmBYOL+fuNOWJ7wSsviEgHvG7H3J4Foe9WR9FDyDsnIttfAmHKijeCbkxIJ4q7Yui9KLdQCL2UcSfLvVtRCU30p0RHAbDGPI5ajnKa2JIWOsFO3a55OGjmJKWRDyeug70FlQGwZ50idytoqXHuIscqXF+XCBpOJ6RWgtgbUtZo9OlANtUv3bowuaXocheuwvOf7qhqZrqnwyaUl1LcQMNX+vckdkqeUk8SmGxqvdLUc3v+RT/T0f0RdPuoXNW+g0qxHZ6UddNXarC9bVmASBhIdGAYI+5OJ51gEyh/G3X3w/ujf5t/Rpl87+jr6br2dEtNhPRR8+yngudA8I3cXkoOrQ649ywVirxWtMg9L+uIkQ4G7Qj7s6/DPK0yxC52XZwjgJ22ZMjVTRWpPxtQcBPiiAVA4D/VzZnTNnIxgGX06qV634vuPUtzpZnP7duCkrCa1mjuxY0wz1CEWAHen0iGJtQx3TbE90LPpuAlVLTqHToyiQXII9pkI6iw+v6aRVtYEKBKEP2Smu5g3Mae9Y8bI0BPDG2Ux1DtJUJ49Q0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
